name: PDF Markdown Artifact Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pdf-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils python3 python3-pip
        pip3 install reportlab
        
    - name: Check PDFs for raw markdown artifacts
      run: |
        python3 .github/workflows/pdf-lint.py
        
    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: pdf-check-results
        path: "*.pdf"